"""Controlled attack simulator for the local TCC laboratory.

The functions in this module do not attack networks, operating systems or
third-party services. They create suspicious access events against the local
SQLite prototype so the monitor can demonstrate defensive detection, response
and logging.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable
from uuid import uuid4

from .database import DEFAULT_DB_PATH, get_connection, utc_now
from .gateway import AccessGateway, AccessResponse


ATTACK_INJECTION = "injection"
ATTACK_DDOS = "ddos"
ATTACK_BRUTE_FORCE = "brute-force"
ATTACK_BUFFER_OVERFLOW = "buffer-overflow"
ATTACK_PRIVILEGE_ESCALATION = "privilege-escalation"

ATTACK_MODE_CHOICES = (
    ATTACK_INJECTION,
    ATTACK_DDOS,
    ATTACK_BRUTE_FORCE,
    ATTACK_BUFFER_OVERFLOW,
    ATTACK_PRIVILEGE_ESCALATION,
)


@dataclass(frozen=True)
class AttackStepResult:
    """One access event generated by a controlled attack scenario."""

    step_number: int
    description: str
    access_log_id: int
    success: bool
    anomaly_score: int
    anomaly_severity: str
    expected_signal: str


def run_controlled_attack(
    db_path: str | Path = DEFAULT_DB_PATH,
    *,
    mode: str,
    request_count: int = 30,
) -> list[AttackStepResult]:
    """Run one controlled attack mode against the local access gateway."""

    if mode not in ATTACK_MODE_CHOICES:
        choices = ", ".join(ATTACK_MODE_CHOICES)
        raise ValueError(f"Modo de ataque invalido: {mode}. Use um destes: {choices}.")

    attack_session_id = uuid4().hex
    gateway = AccessGateway(db_path)
    attack_function = _attack_mode_functions()[mode]
    return attack_function(
        gateway=gateway,
        db_path=Path(db_path),
        attack_session_id=attack_session_id,
        request_count=max(1, min(request_count, 100)),
    )


def _attack_mode_functions() -> dict[str, Callable[..., list[AttackStepResult]]]:
    """Map CLI attack names to their local simulation functions."""

    return {
        ATTACK_INJECTION: _simulate_sql_injection,
        ATTACK_DDOS: _simulate_ddos,
        ATTACK_BRUTE_FORCE: _simulate_brute_force,
        ATTACK_BUFFER_OVERFLOW: _simulate_buffer_overflow,
        ATTACK_PRIVILEGE_ESCALATION: _simulate_privilege_escalation,
    }


def _simulate_sql_injection(
    *,
    gateway: AccessGateway,
    db_path: Path,
    attack_session_id: str,
    request_count: int,
) -> list[AttackStepResult]:
    """Generate rejected table names that resemble SQL injection attempts."""

    payloads = [
        "clientes' OR '1'='1",
        "clientes; DROP TABLE users; --",
        "clientes UNION SELECT senha FROM users",
    ]
    results: list[AttackStepResult] = []
    for step_number, payload in enumerate(payloads, start=1):
        response = gateway.read_table(
            username="analista",
            password="analista123",
            table_name=payload,
            ip_address="203.0.113.10",
            user_agent="attack-sim/injection",
            limit=5,
            event_time=_simulation_time(step_number),
        )
        results.append(
            _record_attack_step(
                db_path=db_path,
                attack_session_id=attack_session_id,
                mode=ATTACK_INJECTION,
                step_number=step_number,
                description="Tentativa controlada de injection em nome de tabela",
                expected_signal="padrao compativel com tentativa de SQL injection",
                response=response,
            )
        )
    return results


def _simulate_ddos(
    *,
    gateway: AccessGateway,
    db_path: Path,
    attack_session_id: str,
    request_count: int,
) -> list[AttackStepResult]:
    """Generate many local gateway requests to mimic a DDoS signal safely."""

    results: list[AttackStepResult] = []
    for step_number in range(1, request_count + 1):
        response = gateway.read_table(
            username="analista",
            password="analista123",
            table_name="clientes",
            ip_address="203.0.113.20",
            user_agent="attack-sim/ddos",
            limit=1,
            event_time=_simulation_time(step_number),
        )
        results.append(
            _record_attack_step(
                db_path=db_path,
                attack_session_id=attack_session_id,
                mode=ATTACK_DDOS,
                step_number=step_number,
                description="Rajada controlada de acessos locais ao gateway",
                expected_signal="padrao compativel com simulacao de DDoS",
                response=response,
            )
        )
    return results


def _simulate_brute_force(
    *,
    gateway: AccessGateway,
    db_path: Path,
    attack_session_id: str,
    request_count: int,
) -> list[AttackStepResult]:
    """Generate repeated failed logins against one known username."""

    attempts = max(5, min(request_count, 20))
    results: list[AttackStepResult] = []
    for step_number in range(1, attempts + 1):
        response = gateway.read_table(
            username="analista",
            password=f"senha-incorreta-{step_number}",
            table_name="clientes",
            ip_address="203.0.113.30",
            user_agent="attack-sim/brute-force",
            limit=1,
            event_time=_simulation_time(step_number),
        )
        results.append(
            _record_attack_step(
                db_path=db_path,
                attack_session_id=attack_session_id,
                mode=ATTACK_BRUTE_FORCE,
                step_number=step_number,
                description="Tentativa controlada de senha invalida",
                expected_signal="multiplas negacoes recentes para o usuario ou IP",
                response=response,
            )
        )
    return results


def _simulate_buffer_overflow(
    *,
    gateway: AccessGateway,
    db_path: Path,
    attack_session_id: str,
    request_count: int,
) -> list[AttackStepResult]:
    """Generate oversized inputs to mimic buffer-overflow pressure."""

    oversized_table_name = "clientes_" + ("A" * 512)
    oversized_user_agent = "attack-sim/buffer-overflow " + ("B" * 1024)
    response = gateway.read_table(
        username="analista",
        password="analista123",
        table_name=oversized_table_name,
        ip_address="203.0.113.40",
        user_agent=oversized_user_agent,
        limit=1,
        event_time=_simulation_time(1),
    )
    return [
        _record_attack_step(
            db_path=db_path,
            attack_session_id=attack_session_id,
            mode=ATTACK_BUFFER_OVERFLOW,
            step_number=1,
            description="Entrada controlada com tamanho excessivo",
            expected_signal="entrada excessivamente grande ou possivel buffer overflow",
            response=response,
        )
    ]


def _simulate_privilege_escalation(
    *,
    gateway: AccessGateway,
    db_path: Path,
    attack_session_id: str,
    request_count: int,
) -> list[AttackStepResult]:
    """Generate attempts where a low-privilege role asks for restricted actions."""

    attempts = [
        (
            "Leitura indevida da tabela salarios",
            lambda: gateway.read_table(
                username="analista",
                password="analista123",
                table_name="salarios",
                ip_address="203.0.113.50",
                user_agent="attack-sim/privilege-escalation",
                limit=5,
                event_time=_simulation_time(1),
            ),
        ),
        (
            "Exclusao indevida de transacao",
            lambda: gateway.delete_transaction(
                username="analista",
                password="analista123",
                transaction_id=1,
                ip_address="203.0.113.50",
                user_agent="attack-sim/privilege-escalation",
                event_time=_simulation_time(2),
            ),
        ),
    ]

    results: list[AttackStepResult] = []
    for step_number, (description, execute) in enumerate(attempts, start=1):
        response = execute()
        results.append(
            _record_attack_step(
                db_path=db_path,
                attack_session_id=attack_session_id,
                mode=ATTACK_PRIVILEGE_ESCALATION,
                step_number=step_number,
                description=description,
                expected_signal="padrao compativel com tentativa de escalada de privilegio",
                response=response,
            )
        )
    return results


def _record_attack_step(
    *,
    db_path: Path,
    attack_session_id: str,
    mode: str,
    step_number: int,
    description: str,
    expected_signal: str,
    response: AccessResponse,
) -> AttackStepResult:
    """Persist one simulated attack step and return its display result."""

    with get_connection(db_path) as connection:
        connection.execute(
            """
            INSERT INTO attack_simulations (
                created_at, attack_session_id, mode, step_number, description,
                access_log_id, expected_signal
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                utc_now(),
                attack_session_id,
                mode,
                step_number,
                description,
                response.log_id,
                expected_signal,
            ),
        )
    return AttackStepResult(
        step_number=step_number,
        description=description,
        access_log_id=response.log_id,
        success=response.success,
        anomaly_score=response.anomaly.score,
        anomaly_severity=response.anomaly.severity,
        expected_signal=expected_signal,
    )


def _simulation_time(step_number: int) -> datetime:
    """Return deterministic timestamps close enough to trigger windowed rules."""

    return datetime(2026, 5, 4, 15, min(step_number, 59), tzinfo=timezone.utc)
